# Site
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
url: "http://www.cecivieira.com/"
google_analytics: 'G-PEG4L84NMR'
disqus: 'cecivieira'
# mailchimp-list: 
include: ["_pages"]
permalink: /:title/
languages: ['pt-br', 'es', 'en']

# Author
authors:
  cecivieira:
    name: Ana Cecília Vieira
    display_name: Ana Cecília Vieira
    avatar: ''
    web: https://cecivieira.github.io
    description: "Cientista de dados em construção, Bibliotecária, entusiasta de transparência de dados e construções coletivas como caminho para transformação social."

# Social media
twitter: https://twitter.com/cecivieira
github: https://github.com/cecivieira
linkedin: https://www.linkedin.com/in/cecivieira/
email: cecivieira@gmail.com

# License
copyright:
    name: CC BY-SA 4.0
    link: https://creativecommons.org/licenses/by-sa/4.0/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-multiple-languages-plugin
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categoria/:name/'
    
# Pagination 
paginate: 30
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, Rakefile]
exclude_from_localizations: ["javascript", "images", "css"]